name: Build

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ development ]

env:
  VERSION_NUMBER: 0.0.${{ github.run_number }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .Net Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore

  deploy:
    needs: build
    if: ${{ github.ref_name == 'main' && github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login Dokcer.io
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PWD}}
    - name: Build and Push
      uses: docker/build-push-action@v3
      with:
        context: ./src
        file: ./src/PiTimeline/Dockerfile 
        platforms: linux/arm/v7
        push: true
        tags: edentidus/pitimeline:${{env.VERSION_NUMBER}},edentidus/pitimeline:latest