name: Build

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ development ]

env:
  VERSION_NUMBER: 1.0.${{ github.run_number }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .Net Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: dotnet restore
    - name: Build and Test
      run: |
        dotnet test --configuration Release --no-restore
        cd ./src/PiTimeline/ClientApp
        npm install
        npm test -- --coverage
        
  deploy:
    needs: build
    if: ${{ github.ref_name == 'main' && github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .Net Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        
    - name: Build and publish project
      run: dotnet publish --configuration Release -o ./publish
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login Dokcer.io
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PWD}}
        
    - name: Build image and Push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./src/PiTimeline/Dockerfile 
        push: true
        tags: edentidus/pitimeline:${{env.VERSION_NUMBER}},edentidus/pitimeline:latest
        build-args: source=./publish
