name: Build

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ development ]

env:
  VERSION_NUMBER: 0.0.${{ github.run_number }}
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .Net Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
  
  deploy:
    needs: build
    if: ${{ github.ref_name == 'main' && github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .Net Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Build the Docker image
      run: |
        echo "Build docker image with version $VERSION_NUMBER"
        docker build ./src --file ./src/PiTimeline/Dockerfile --tag edentidus/pitimeline:$VERSION_NUMBER --tag edentidus/pitimeline:latest
    - name: Login Dokcer.io
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PWD}}
    - name: Push image
      run: |
        docker push edentidus/pitimeline:$VERSION_NUMBER
        docker push edentidus/pitimeline:latest
